// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB689YkBWnKcYLMkuvUiTag71G-OLAe_cc',
    appId: '1:219949791191:web:860e95a57262e0e0de3d92',
    messagingSenderId: '219949791191',
    projectId: 'linknotes-f5d10',
    authDomain: 'linknotes-f5d10.firebaseapp.com',
    storageBucket: 'linknotes-f5d10.appspot.com',
    measurementId: 'G-F0365DJK6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1pipzKoTGu-8iP8U1-JCOlGK0SG8OSd8',
    appId: '1:219949791191:android:c5386558d740d461de3d92',
    messagingSenderId: '219949791191',
    projectId: 'linknotes-f5d10',
    storageBucket: 'linknotes-f5d10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6JOC5jmAJkAhxjTvilwJKf6rWBbHpjGw',
    appId: '1:219949791191:ios:42e57700cc0e9b6fde3d92',
    messagingSenderId: '219949791191',
    projectId: 'linknotes-f5d10',
    storageBucket: 'linknotes-f5d10.appspot.com',
    iosBundleId: 'com.example.linknotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6JOC5jmAJkAhxjTvilwJKf6rWBbHpjGw',
    appId: '1:219949791191:ios:23c4698fa9d137f8de3d92',
    messagingSenderId: '219949791191',
    projectId: 'linknotes-f5d10',
    storageBucket: 'linknotes-f5d10.appspot.com',
    iosBundleId: 'com.example.linknotes.RunnerTests',
  );
}
